### ISSUE TITLE
Documentation about cross compilation capabilities

### ISSUE THREAD

**Issue by lu-zero** [waf-project/waf#1560]
Right now looking for that information leads to the quite convoluted (and highly involving) way suggested by Samba and few post to the mailing list.

Would be possible to support `cross-prefix` `target-os` `sysroot` and `arch` out of box?

Secondarily would be possible to have a mean to pass `target` and `host` variants for the compilers in case there is the need to compile helper programs to be run to generate files?

**Comment by ita1024** [comment]
The samba build uses a fork of waf 1.5 which is unsupported. The instructions that they gave to you are the ones that you must use for the samba build.

Cross-compilation is a complicated problem because each project can have custom needs, so one should start by enumerating the requirements and look into the examples such as demos/variants or cfg_cross_gnu.py

Specific variables can be set in target variants, but there is a variety of ways to implement it, and no special mapping to the variables above is provided out-of-the-box.

**Comment by lu-zero** [comment]
Would be possible to put the paragraphs above in the waf-book?
