### ISSUE TITLE
Set out directory to current directory if it is not a source directory

### ISSUE THREAD

**Issue by lilrc** [waf-project/waf#1564]
I know that waf separates build and source directory by default. The default is to have a subdirectory of the toplevel source directory. This is a good default, IMHO and the aim of this issue is not to change it.

However, when doing out-of-source builds it is possible to cd into the build directory and invoke the waf binary that relies in the source directory, but this builds the project in the toplevel source directory (as described in the first section). Of course the `--out` argument can be used to explicitly point output to the desired build directory (the current directory), but I would suggest that waf should have the following logic:

Check whether the current directory is a source directory (for example it contains a wscript). If so, build in the default build subdirectory (as described in the first section). Otherwise (if the current directory is outside the source directory) set out directory to the current directory if not already set using `--out`.

Both CMake and autotools have this logic, so why shouldn't waf?

**Comment by ita1024** [comment]
We used to have such functionality (gcc-style configuration) and this was removed due to lack of usage.

Another aspect is that it is usually safer for projects to rely on a standard project folder. More configuration means more opportunities for things to go wrong.

You are yet welcome to implement your own waf derivative by using [the buildsystem kit](https://github.com/waf-project/waf/tree/master/build_system_kit) if necessary.

**Comment by lilrc** [comment]
Well, it is always easier to assume everyone compiles their software exactly the same way. It is also quite nifty to assume everyone is using Ubuntu with exactly the same packages installed and have exactly the same needs. I guess you see my point. ;) Some robustness is never bad, IMHO.

Anyway, I won't push any further on this issue since there is a (clumsy) workaround.
