### ISSUE TITLE
Archiver commands splits output names from output flag when it shouldn't

### ISSUE THREAD

**Issue by haraldkl** [waf-project/waf#1680]
The stlink_task in ccroot.py defines the run_str as:

    run_str = '${AR} ${ARFLAGS} ${AR_TGT_F}${TGT} ${AR_SRC_F}${SRC}'

That is, targets are seemingly to be appended directly to the AR_TGT_F. For the msvc this seems to be required, the AR_TGT_F is set to "/OUT:" and the goal would be to have the library name directly attached to it. But it isn't, which I suppose is due to the command construction for non-shell commands. We therefore, get something like

    ['lib.exe', '', '/OUT:', 'libflu.a', ...

instead of

    ['lib.exe', '', '/OUT:libflu.a', ...

Maybe this could be worked around by turning the stlink_task into a shell execution class, but that's probably less desirable. How could this be resolved correctly?

**Comment by ita1024** [comment]
In waf 1.8, make sure that your class is using `exec_command_msvc`. Does Visual Studio provide a Fortran compiler now?

**Comment by haraldkl** [comment]
No, I don't think it does. This project is a mixed C/Fortran project. Where a C compiler is required to compile all the C sources, in this case it is msvc. As far as I can see, msvc set AR_TGT_F no matter which archiver is to be used. Anyway the choice of the archiver should not matter. Thus, even if the archiver is from visual studio, this should still be fine for the fcstlib (which is just the same as stlink_task).

I propose to add fcstlib to the list of classes to wrap in msvc. But this would require import fc in msvc.

**Comment by ita1024** [comment]
Visual Studio and other compilers cannot share the same environment as the variables names are shared. The recommendation is to either:
1. Ensure that the archiver is Visual Studio (features="fc c cstlib")
2. Ensure that the environments are set properly:
   - Decompose the target in several task generators (bld.stlib / bld.objects)
   - Or unset env.AR_TGT_F if the archiver is meant to be the Fortran one

Since the build is performed on Windows, using the Visual Studio archiver (1) seems to be a sensible choice.

**Comment by haraldkl** [comment]
Great! Thanks a lot for your, as always, fast support! Using cstlib should be fine for me and it is most easily implemented, so I'll take option 1 ;)
