### ISSUE TITLE
Weak order constraints (for .cpp compilation) are non-deterministic

### ISSUE THREAD

**Issue by q-p** [waf-project/waf#1682]
Weak order constraints (i.e. hinting compilation order) as described in the wafbook Section 8.2.3 do not work deterministically. I'm not even sure why (or if) it seems to work for the example case of a single high-priority job,

This problem seems due to the fact that `Runner.Parallel.postpone` randomly inserts either at the front or at the back, and this mechanism is used after the constraints have been set.

I'm not sure whether this behaviour is related to a particular task classes or a general problem.

Example:
```python

# build order hints: instantiations > loop > everything else
_hint_compilation_order('cxx', [re.compile('.*Instantiat.*', re.I), re.compile('.*Loop.*', re.I)])

def _hint_compilation_order(task_class_name, input_name_regexes):
    # insert our function for ordering tasks into waf's Task class
    from waflib import Task
    old_set_file_constraints = Task.set_file_constraints
    def prio_set_file_constraints(lst):
        # compute the priority for each task and store in task2prio (if non-default)
        task2prio = {}
        num_priorities = len(input_name_regexes)
        for t in lst:
            if t.__class__.__name__ != task_class_name:
                continue
            for p, regex in enumerate(input_name_regexes):
                for i in t.inputs:
                    if regex.match(i.name):
                        # 0 => normal, -1 => worst match, ..., -num_priorities => best match
                        task2prio[t] = -(num_priorities - p)
                        break # inputs
                if t in task2prio:
                    break # regex
        lst.sort(key=lambda x:(task2prio.get(x, 0), x))
        old_set_file_constraints(lst)
    Task.set_file_constraints = prio_set_file_constraints
    # fix postponing tasks to be deterministic in waf's Runner.Parallel class
    # (it randomly appends or prepends to the frozen list)
    from waflib import Runner
    Runner.Parallel.postpone = lambda self,tsk:self.frozen.append(tsk)
```

**Comment by ita1024** [comment]
This is correct. The function `set_file_constraints` is called once per group of tasks. During the build, all the tasks in the list "outstanding" are processed before the discarded tasks marked "frozen" are processed again. When lots of tasks are waiting, the build will maximize cores usage over initially given priorities by ignoring the initial schedule. Some additional code is thus necessary in order to implement a proper priority system.

The following [old example](https://github.com/waf-project/waf/blob/master/docs/book/examples/tasks_weak2/wscript) shows how to work re-order the queue dynamically. Such technique works best when there are few dependencies between blue and other tasks.

Now if there are waiting tasks, it can be useful to place in front only the tasks that can immediately run. In the case of C/C++ builds one may rely on file constraints which are reflected by the task `tsk.run_after` set. I have added a newer [example](https://github.com/waf-project/waf/blob/waf-1.9/playground/weak_constraints/greenfirst.py), check it out.

**Comment by q-p** [comment]
Thanks. I have to admit I understand a fair bit less of why certain stuff has to happen in the new example you provided (especially with comments such as "may seriously degrade performance" :smile:) and I'll probably stick to my current work-around of forcing `postpone()`ing to the end.

It would be helpful for my use case (some `.cpp` files with many instantiations of large templates) to have a general `priority` attribute for tasks and always preferring ready-to-run tasks of higher priority. It's a shame this seems rather difficult (or at least covered by caveats) to monkey-patch in.

**Comment by ita1024** [comment]
In C++ the obvious approach would be of course to provide classes, and add a nice scheduler with priorities. Yet Python is not C++, and it is just too easy to add bloat that will make builds very slow and memory hungry.

Since such requirements are infrequent and are project-dependent (the old example was last written in 2012) and since plugging in additional behaviour(s) is rather easy (monkey patching is another name for aspect-oriented programming), no changes to the current framework or to the documentation are necessary.

Note: deterministic scheduling order can degrade build performance in builds having lots of dependencies (a lot of iterations to know which task to run first), so you should probably not do that without measuring the outcomes.
