### ISSUE TITLE
source not found error when source is parent directory of target

### ISSUE THREAD

**Issue by AndCycle** [waf-project/waf#1724]
I just caught on this after hours of try/error,
which I haven't find the correct way to do on google or this is actually a bug

here is the minimal code to trigger it,

```
def build(bld):
    bld(rule='mkdir ${TGT}', target='foo')
    bld(rule='touch ${TGT}', source='foo', target='foo/bar.txt')
```

> 
source not found: 'foo' in bld(features=[], idx=2, meths=['process_rule', 'process_source'], prec=defaultdict(<type 'list'>, {}), _name='foo/bar.txt', source='foo', rule='touch ${SRC}/${TGT}', mappings={}, path=/tmp/sample/src, posted=True, target=['foo/bar.txt']) in /tmp/sample/src

**Comment by ita1024** [comment]
Not a bug: the build creates only files, not folders (Waf 1.8).

**Comment by AndCycle** [comment]
thanks for the answer,
where should I read on waf book to proper guide the build process if it involve folders?

this code below do pass the build process which make me really confuse when I hit this

```
def build(bld):
    bld(rule='mkdir ${TGT}', target='foo')
    bld(rule='touch ${TGT}', source='foo', target='bar.txt')
```

**Comment by ita1024** [comment]
There is no section on that yet because trying to create folders usually indicates design concerns that usually lead to a variety of issues such as race conditions and interoperability issues.

In general, folders should be created directly by the build scripts (creating folders in parallel is a bad idea) whenever they are executed (`os.makedirs` is not a bottleneck) and only if really needed (folders for targets in the build directory are already created automatically). In practice this means creating folders and passing corresponding Node objects as source/target if strings do not do it.

If you still have a super-important corner-case, you can play with the branch waf-1.9 but that will not earn you much as `mkdir` is not portable:

```
def build(bld):
    foo = bld.path.make_node('foo')
    bld(rule='mkdir -p ${TGT}', target=foo)
    bld(rule='touch ${TGT}', source=foo, target=foo.make_node('bar'))
```

**Comment by AndCycle** [comment]
@ita1024 
got it, gonna read around waflib.Node.Node,
thanks
