### ISSUE TITLE
qt5 and python

### ISSUE THREAD

**Issue by fedepell** [waf-project/waf#1772]
Hi!
I'm working on a project in Python with QT5. Also for Python there are a few steps to be done to convert files (for example .ui5 or .qrc) to .py in a similar fashion as in C++ (where they get converted to headers or to objects).

My idea was to implement this in the qt5 module checking the feature and then using the right tool accordingly. I have an initial demo version here:
https://github.com/fedepell/waf/tree/pyqt5

Of course is not finished at all, but before investing too much time into it I wanted to get an opinion from you if this should be the way to go or if I'm totally off track.

What do you think?

Should this be the way to go of course things have to be finished in detail (ie. configuration based on C++ and/or Python depending on which is loaded, finish for other types of files and so on). In that case one question is also since there are mainly two Python bindings to QT5 (pyqt5 which I'm targeting now but also pyside2) should we differentiate them at configuration stage?

As a sample usage:
```
    bld(features='py qt5', source=bld.path.ant_glob('src/*.ui'))
    bld(features='py qt5', source=bld.path.ant_glob('*.qrc'))
```

Thanks a lot!
F.

**Comment by ita1024** [comment]
I am really unsure about the implementation. The qt5.py file is really meant for C++ support, and since it is uncommon to mix pyqt and c++ i believe it makes much more sense to provide a pyqt5.py file instead.

**Comment by fedepell** [comment]
Understood! Sure no problem also in doing a separate file. My only worry was that some code would be most probably duplicated. But for sure would be much cleaner. So if this is the best solution in your opinion I can create a separate file and proceed.

Thanks!
F.

**Comment by ita1024** [comment]
Yes.

**Comment by fedepell** [comment]
I did a first version as an extra here:
https://github.com/fedepell/waf/tree/pyqt5-separate

It manages ui to py and qrc to py, and then py compilation using the standard python module. I kept the qrc dependencies search as in c++ (works well) and the language features. I tried it on my projects and does all that I would currently need.

It searches for both pyqt5 and pyside2 tools (in this order) but probably I could put an option (good idea?) to force one of them.

Not to have clashes where a QT5 project uses both C++ and Python (maybe not that often but) should we explicitly check for features in both the qt5 and pyqt5? (otherwise you may get the same .ui passed by both if I didn't understand something wrong)

Thanks!
F.

**Comment by ita1024** [comment]
- The indentation mixes tabs and spaces, use tabs
- Please add a test directory in `playground/` so that we can see how this works.
- There is no need for `qtdir`, remove that. Unlike for the C++ case, there is no need for us to look beyond the contents of `PATH`.
- If there are no options, then there is no need for such function, same for line 217 in `find_pyqt5_binaries`
- `find_program` can check for multiple programs, so there is no need for `find_bin`
- Unlike the Qt5 case, I think an error should be raised during the configuration if xml support is missing (lines 41 and 204)
- Remove the name from line 3, you should be the only author
- The documentation is unclear: how do you "Reference the qrc resources files or ui5 definition files as your sources"?
- There is no "link" therefore `@after_method('apply_link') ` is nonsense.
- Avoiding file extension clashes with other processors can be achieved in a variety of ways:
  * the files can be added to some other attribute than `source` and processed by a specific task generator method
  * the task generator may provide custom mappings that override the defaults (`self.mappings = {'.ui': create_pyuic_task}`)

**Comment by fedepell** [comment]
Thanks a lot for the detailed feedback! I should have fixed with the last commit to same branch most of the issues except:

-) I'll add an example in playground (I currently have other devs code compiling, so need to do a Hello World)

-) I don't understand why the XML support should raise an error here and not in C++ case. In both I guess what we miss without XML is the check of dependencies inside the qrc (so to rebuild the qrc if one of the files referenced inside change). Why should the behavior in general be different between the two versions? (I'd expect either both to fail or both to just do a warning, that's why I stayed on the warning side as in C++)

-) I'll check better the last point to understand better how to proceed, thanks for the indications!

Thanks!
F.

**Comment by ita1024** [comment]
And i think this can be closed now.

**Comment by fedepell** [comment]
hi!
sorry didn't complete yet since on vacation. i'll commit a playground sample asap and fix what remains and do a pull req. 
thanks!
f.

**Comment by fedepell** [comment]
Hi!
While preparing the playground sample I found a problem in the install phase. I found a solution but I don't think it's the right way to do so I'm asking for your help.

Basically the thing is that from the .ui/.rcc I create a py in the build directory which is fine.
Then from the .py in build directory I call process_py which creates the pyc/pyo. But since the source is in the build directory the install will try to install this with the build/XXX directory structure.

Now the easiest way to me to fix this was to prepend the build directory to the install_from attribute (if present, if not then just define install_from as the build directory) and it actually seems to work (I tried various combinations with and without install_path, with and without install_from, in nested directories) but I'm not so convinced of how I did it (using Context to get the build dir and to get the top dir to make all paths relative as needed by install_from). 

Could you see if this looks horrible and how could I fix it better? I committed in
https://github.com/fedepell/waf/tree/pyqt5

And the code is for example:

```
@extension(*EXT_RCC)
def create_pyrcc_task(self, node):
        "Creates rcc and py task for ``.qrc`` files"
        rcnode = node.change_ext('.py')
        self.create_task('pyrcc', node, rcnode)
        if self.install_from:
                pyd = Context.out_dir[len(Context.top_dir)+1:] + str(self.install_from)[len(Context.top_dir):]
        else:
                pyd = Context.out_dir[len(Context.top_dir)+1:]

        self.install_from = self.path.find_dir(pyd)
        self.process_py(rcnode)
```

Thanks!
F.

**Comment by ita1024** [comment]
Are you assuming that the build directory `out_dir` is always under the source directory `top_dir`? This is not a valid assumption.

Does the `install_from` parameter makes any sense for generated python files? Is there a folder hierarchy?

If this is not the case, then `self.path.get_bld()` should be sufficient. Else, if `install_from` is already a Node object, just return `install_from.get_bld()`. Otherwise `self.path.get_bld().find_node(self.install_from)` should give the Node object seen from the build directory. Please use `Node` objects and verify that they are not None.

**Comment by fedepell** [comment]
Thanks a lot for the hint, work perfect! I fix now and add playground and commit!

I wanted to keep the install_from so it is all perfectly compatible with the python tool. And in my case for my project it is needed too (so a python module in copied with a relative path and also the py that are generated from a ui are copied there in the same place)

Thanks!

**Comment by ita1024** [comment]
That was a applied so we can close this now.
