### ISSUE TITLE
find_node vs find_resource in gccdeps

### ISSUE THREAD

**Issue by artiomn** [waf-project/waf#1789]
In the function gccdeps.path_to_node, find_resource() doesn't find resources in the `build` directory, like: `build\packages_cache\zlib-1.2.8-17\build\include\`.
find_node() finds.

**Comment by ita1024** [comment]
Well, no, this most likely means that your build is not declaring any output header files in the build directory. See 
[this example](https://github.com/waf-project/waf/blob/master/playground/dynamic_build2/wscript#L31) to enable reading files placed in the build directory.

You should also check the build order so that the header is actually created before c/c++ files are processed.

**Comment by artiomn** [comment]
What's it? read_files() doesn't produce anything, and bld.program doesn't depend of read_files.
How does it work?
It's not obvious, a little bit.

**Comment by ita1024** [comment]
The example shows how files can be declared dynamically, in that particular case a source file is contained in the `.tar` file which is uncompressed in the source directory. The point is, one *must* declare the files somehow before dependencies are calculated.

We will not make such changes to `gccdeps` because this conceals bugs and affects performance negatively.

**Comment by artiomn** [comment]
I understood, what this example does. But I don't understand how.

**Comment by ita1024** [comment]
The chapter 10 in The Waf Book was updated, so you should start by reading it.

That function calls ant_glob lists files in the build directory; since it changes the Node structure it is important that it runs alone. This is achieved by defining a single task generator on line 31 which enables a single task instance. Since it is defined alone in a build group, the task will run when no other does.

**Comment by artiomn** [comment]
Ok. Thank you.
