### ISSUE TITLE
Using `after` keyword on the non-rule based task generators

### ISSUE THREAD

**Issue by artiomn** [waf-project/waf#1821]
If I try this, I have message, like this (from the errcheck):
"Erroneous order constraint 'after' on non-rule based task generator bld(tmp_use_not=set([]), linker_flags=['/SUBSYSTEM:WINDOWS,5.01'], asflags=[],"

And, I get spontaneous errors on Windows (because some files is have been using during manipulation with them in postbuilds). 
I can't use `use` keyword, because C link_task expects to find import libraries, but I want to run build after building some tools and tasks depend on executables. :-/
Using groups (like in 11.1.1 Wafbook chapter) also isn't a best way, because I don't know, which task will be used by the current task, before it will be created, and some tasks may be had been created before this point.

Why I cant use `after` in this (natural, I think) way?

**Comment by ita1024** [comment]
The message is correct, the statement `after` has no effect because it only affects `Task` objects and not `Task Generator` objects. Since a task generator object may define a lot of tasks, should the `after` keyword apply to all of them or to only one of them?

The solution is really define task generator methods to access the tasks from a previous task generator as you need them. And if you really think that the after keyword would make sense there, you can certainly provide your own implementation (using a task generator method too).

**Comment by artiomn** [comment]
> Since a task generator object may define a lot of tasks, should the after keyword apply to all of them or to only one of them?

I think, `after` keyword in a task generator must provides task generators names.
Tasks in provided generators must be run before any task, created by the current task generator (with a keyword).

> And if you really think that the after keyword would make sense there, you can certainly provide your own implementation (using a task generator method too).

Ok.

**Comment by artiomn** [comment]
Waf 1.9.4.

**Comment by ita1024** [comment]
Once again, the "after" keyword specifies a build order on *Task class* names. Recycling this for *task generator objects* names is really wrong. Rule-based generators define exactly one *task class* with the name specified by the rule.

**Comment by ita1024** [comment]
The documentation is not unclear about this so there is no change to be done about this matter.
