### ISSUE TITLE
ant_glob execution time

### ISSUE THREAD

**Issue by fominok** [waf-project/waf#1849]
I don't know if this is a normal behaviour or not, but it doesn't seem natural for me:
```
def build(ctx):
    ctx(rule='gcc ${CFLAGS} ${SRC}', source='src/main.c src/func.c')
    ctx.add_group()
    ctx(rule='gcc ${SRC} -o any', source='build/main.o build/func.o') # It works
    ctx(rule='gcc ${SRC} -o any', source=ctx.path.ant_glob('build/*.o')) # But it doesn't

```

On the first execution last task fails, because it cannot find object files, produced by first task. On second execution there is no errors. I think `ant_glob` computes before first task finish, when there are no *.o files yet.

**Comment by ita1024** [comment]
1. The function "build" is executed at once, it does not stop and wait on each line as that would break parallel builds. It would also make `add_group` redundant
2. A callback function is needed, either in the form of a task generator method or as a dummy task as illustrated in https://github.com/waf-project/waf/blob/master/playground/dynamic_build2/wscript#L31
3. As the method `ant_glob` clears node objects that have no corresponding file-system objects, it should be run on the build directory only with some precautions (try `waf -v`)

**Comment by fominok** [comment]
Thanks for your reply @ita1024 .
Without `add_group` it won't work at all. Somewhere in Waf book: "Add a new build group to make certain the compiler is complete before processing the next tasks". I think it will compile sources in parallel, but won't start next group's tasks until we have all object files.

Unfortunately, I don't get that example on your link and how to adapt it to my problem. Do you know how to force `ant_glob` work within the task, where I call it? In my example task2 runs strongly after task1 and I'm sure that glob doesn't.

**Comment by ita1024** [comment]
I realized that the example that you are setting up looks like a very crude translation of some Makefile. I recommend try to leverage the existing infrastructure of high-level targets instead of creating an unportable wrapper for low-level command-lines:
https://github.com/waf-project/waf/blob/master/demos/c/shlib/wscript_build#L15

If you are still trying to list files dynamically, then please read through the answer above carefully once again. The following example could be followed as a recipe: https://github.com/waf-project/waf/blob/master/playground/dynamic_build/wscript#L56
