### ISSUE TITLE
How can I create a BuildContext like Context without requireing configure

### ISSUE THREAD

**Issue by drahnr** [waf-project/waf#1871]
waflib.Context.Context is not sufficient to replace BuildContext in the below code

```
from waflib.Context import Context
from waflib.BuildContext import BuildContext

class codestyle(Task.Task):
	color = 'PINK'
	def run(self):
		node = self.inputs[0]
		cmd = ['clang-format', '-i', node.abspath()]
		try:
			subprocess.call(cmd)
		except subprocess.CalledProcessError as e:
	                return Task.EXCEPTION
		else:
	                return 0

@TaskGen.feature('codestyle')
def post_codestyle(self):
        for node in self.to_list(getattr(self,'styleme', [])):
                tsk = self.create_task('codestyle', node)


def clangfmt_fun(ctx):
        nodes = ctx.path.ant_glob('src/**/*.[ch]') + ctx.path.ant_glob('src/**/*.[ch]pp')
        ctx(features=['codestyle'], styleme=nodes)
        // other commands for other source types..
        // lint

class clangfmt(BuildContext):
        cmd = 'clangfmt'
        fun = 'clangfmt_fun'
```

**Comment by ita1024** [comment]
What is your question? Are you trying to run a build without configuring the project? In that case, why not use `Configure.autoconfig`? Why not run commands directly through `bld.exec_command`?

**Comment by drahnr** [comment]
This waf target is supposed to be runnable even when configure fail, as such autoconfig fails.

Yes, `exec_command` would be a better choice.

Still does not solve the problem of the bld context requiring configuration.

**Comment by ita1024** [comment]
Builds not only create data as file, they also update build meta-data required to detect when targets are up-to-date. The configuration phase creates the area where this meta-data (and other meta-data) is stored. While most context subclasses are stateless, the BuildContext subclass ones are stateful.

Though this is not a recommended approach, it is possible to run a build in a way that bypasses configuration requirements by adding a constructor (an `__init__` method) to the subclass. The attributes `top_dir`, `out_dir`, `run_dir`, `cache_dir`, `out_dir`, `all_envs` and `env` need to be initialized in order to let the methods `init_dirs` and `load_envs` succeed. There is no direct example, but some inspiration can be found in the method `Configure.run_build` (it uses composition instead of inheritance).

**Comment by drahnr** [comment]
Thanks!
