### ISSUE TITLE
Python installation path may be incorrect on some distros

### ISSUE THREAD

**Issue by eric-s-raymond** [waf-project/waf#1897]
NTPsec is having some installation problems that seem to seem to trace back to a difference of opinion between various distributions over whether Python user libraries should be installed in a directory with basename site-packages or dist-packages (and thus how PYTHONPATH is set).

Our waf recipe works in the first case but not the second; the symptom is that we have to add the site-packages directory to PYTHONPATH by hand.

The proper way to compute this directory is discussed here:

http://stackoverflow.com/questions/122327/how-do-i-find-the-location-of-my-python-site-packages-directory

**Comment by ita1024** [comment]
Given the long history of `waflib/Tools/python.py` and the huge amount of installation problems found over time, I would like you to show me exactly what kind of change you are actually suggesting (patch).

The suggestion `import site; site.getsitepackages()` does not seem to be applicable because the result is not usable in Python 2.5 or 2.6 which Waf supports. Furthermore, the pythondir value is calculated based on the user-provided installation prefix. The current implementation already uses `distutils.sysconfig.get_python_lib` internally (consult your `config.log` for details).

Note: the python installation directory may be provided through `waf configure --pythondir` / `os.environ.PYTHONDIR`.

**Comment by eric-s-raymond** [comment]
I can't five tyou a patch, I don't know waf internals well enough.  Will a recipe to reproduce the problem suffice?

**Comment by ita1024** [comment]
No, that is not sufficient, please provide "the proper way to compute that directory" that you suggested. Regressions are too easy to introduce.

**Comment by ita1024** [comment]
Still waiting for information.
