### ISSUE TITLE
msvc autodetect?

### ISSUE THREAD

**Issue by ieei** [waf-project/waf#1907]
Today I decided to upgrade waf (1.8x to 1.9.7) for my c based library https://github.com/ieei/rlib which builds on multiple platforms. Uses Travis and Appveyor for CI. For all platforms I depend on waf to pick compiler.

I discovered that running 1.8.x MSVC 14.0 is chosen on Appveyor, but with 1.9.7 it chooses MSVC 10.0. Manually doing `waf configure --msvc_version="msvc 14.0"` is my current workaround, but shouldn't it default to the newest version of visual studio that's available on the system?

Please just close this issue if this is by design, I haven't had much time looking into it, but wanted to relay this observation anyway.

**Comment by ita1024** [comment]
No idea. Please attach the config.log file.

**Comment by ita1024** [comment]
The compiler detection should really be the latest.

**Comment by cconverse711** [comment]
Looks to me like it's still selecting the older version. At least it is for me with both msvc 14.0 and 15.0 installed.

I think the problem is that the versiondict keys should no longer be reversed since versiondict returns the latest first (in setup_msvc):
`desired_versions = conf.env.MSVC_VERSIONS or list(reversed(list(versiondict.keys())))
`

**Comment by BazaAMS** [comment]
Google Photos

Марисолька TV shared an album with you:  
https://photos.google.com/share/AF1QipOyCePhcWyzxYAW-0oju7BA1MPFvjs4J8wDxgxINMUoKQ-kWB4HQtcckIlXsdirDg?key=MFoyQWhGdWZtU1VxSU5fWTF4d1A3Wm1JY1hmMnFR

View photos here:  
https://photos.google.com/share/AF1QipOyCePhcWyzxYAW-0oju7BA1MPFvjs4J8wDxgxINMUoKQ-kWB4HQtcckIlXsdirDg?key=MFoyQWhGdWZtU1VxSU5fWTF4d1A3Wm1JY1hmMnFR

You received this mail because Марисолька TV shared these photos with you.  
If you no longer wish to receive email notifications of shared photos,  
unsubscribe here:  
https://notifications.google.com/unsubscribe/AJ7SsMkah_cG4rlo4yudYnxWRDuGoORIJ_TgPEZh58DRq0XwuuSYs3urabnrkHFz883kk8oSm664-r2-FxJlUQRj6haeIwYhrDoGJzPB4YlWphr0XLuvOBeMgZHWKp-S2lLYzX9i9YxvHq6Iu_s6nUk5K6hlGrRwCVvi9ghEenbmSZ00rhPjAqEP-U6DUL4Gt_nqabH3qydlMCdxAeGXJRCU3yKEOFQQP5hdoNlco1_9oo4Z5MzP4YyEaFHC7eXlI2wrHbKM38Eq

Get Google Photos (https://google.com/photos)

Google LLC, 1600 Amphitheatre Pkwy, Mountain View, CA 94043 USA
