### ISSUE TITLE
Xcode6 and build

### ISSUE THREAD

**Issue by bestlem** [waf-project/waf#1939]
I tried the xcode6 example in playground.

waf configure and waf xcode6 (and any combination works- you get an Xcode project .

However waf build fails with a python backtrace ending in
  File "/Users/mark/src/cpp/waf/playground/xcode6/wscript", line 43, in build
    tg = bld.framework(
AttributeError: 'BuildContext' object has no attribute 'framework'

Debugging requires more knowledge than I have but the code seems to match the Waf book
But I note when the build runs the bld object is a waflib.Build.BuildContext object and doesn't this need to be an xcode6 object to understand the framework method.

**Comment by ita1024** [comment]
That is a user-contributed which is unsupported. If you have an idea on how to fix the example feel free to submit a pull request.

**Comment by bestlem** [comment]
That is the problem I don't understand the internals of waf well enough.

My first question here is how do you create a BuildContext that is a subclass and not that actiual class.
Is there a supported example of using a subclass of BuildContext

**Comment by ita1024** [comment]
There are examples in the documentation, but start with the following:

1. The xcode module overrides/provides program/stlib which are valid targets (they work for the build) because they are provided elsewhere. The "framework" and other aliases are not provided anywhere and thus cannot be expected to work in builds. The alias "exe" provides one warning for example
2. The example does not detect any c/c++ compiler so the regular targets cannot build anything.
3. The attribute "source_files" is not processed by regular targets ("source" is)
