### ISSUE TITLE
Distributed Build implementation through Remote execution of tasks through python DASK/Multiprocessing

### ISSUE THREAD

**Issue by sarvi** [waf-project/waf#2082]
I am experimenting with Distributed builds with WAF.
The approach I am trying is to transparently distribute build tasks across multiple nodes, reading and writing to a common NFS workspace.
The goal is to expand all variables locally within WAF and only do the exec_command() on the remote node.

I need some help figuring out what is the best/scalable way to achieve this. 
Just replacing exec_command with a remote version of exec_command would still mean that remote execution call is still executed within a thread that then waits for the result, hence taking up a thread for the duration of the execution of the command on the remote machine.

I was wondering if this would further need extensions to runner.parallel/spawner/consume to replace threads with remote consumer of sorts.

Any advice on this would be most helpful

**Comment by sarvi** [comment]
Yes it does.  This helps.
I tried replacing Utils.py:run_process with a remote_run_process that uses python/dask module for remote execution. 
I am using a ../waf-2.0.2/utils/genbench.py ./ 2000 100 15 5
To just understand overhead, I first ran it using the local 16 cores only,  with and without distributed build changes. 
And I am seeing 24min Vs 13 minutes. 
So it is clear the overhead is high, So I need to look at batching tasks together to optimize on that.

**Comment by ita1024** [comment]
Those tasks are very short-lived and may not be very realistic; the memory and network usage are likely to be significant. Try `bld.load('nobuild')`, that should give you the shortest full build time achievable.

**Comment by justinfx** [comment]
@sarvi did you make any progress on this that you are able to share? I was thinking about a similar solution for distributed subprocesses, but to do it via FaaS functions (running as docker containers on a Kubernetes cluster). That way it is completely scalable and load balanced along with other docker containers that share the same compute resources.

**Comment by sarvi** [comment]
@justinfx  I went as far as testing out WAF with DASK, and I think that part is viable.
And it should work with Kubernetes clusters as well.

Another problem that needs to be solved is the NFS client caching that can make incremental builds unreliable, in such a distributed build system.
When one distributed agent reads and writes an object file, the next agent running the next task/job that depends on this object file, should reliably get the new object and not the one from its own NFS client cache, in incremental builds.

The problem is that there doesn't seem to be a reliable way of making this happen.  Using NFS mount options can be made NOT cache aggressively, but that would kill performance another way. Since the bulk of the operations in a very large build tends to be reads with very few writes, you do want reads to be cached. Except when the file being read has changed. because of another job updating/writing to it.

I have some potential ideas, but havent had a chance to try any of them.

If you have considered this problem and have any suggestions I am all ears.

**Comment by justinfx** [comment]
>  I went as far as testing out WAF with DASK, and I think that part is viable.
And it should work with Kubernetes clusters as well.

What were the modifications you ended up having to apply? Did you need to do more than just swapping out the `run_regular_process()` to do a remote call instead of a local subprocess? Did you just use the existing jobs number semantics to control the number of concurrent distributed tasks? I'm curious if whatever you tested is generic enough to call any defined "subprocess.Popen" interface, be it DASK or a FaaS function running on K8s cluster. 

> Another problem that needs to be solved is the NFS client caching

Did you hit real problems with NFS or is this theoretical? We use NFS mounts exclusively for all of our distributed work, both on users workstations, and on our render farm (distributed compute). If I understand correctly, `close()` calls will always flush to the NFS server for writers. And readers will always get a consistent read when doing `open` or `fopen`. So the thing that could be stale is the attributes or directory listings. I could see this being a problem if HostB needs to check the mtime of object files that were just overwritten by HostA. But I wonder if that problem only applies to certain situations in the case of a Waf dependency graph. 

1. TaskA on HostA is overwriting fileA.obj
2. TaskB can't start until TaskA is successful.
3. TaskA finishes writing and closes file. Syncs to NFS.
4. TaskB unlocks and already knew its input was fileA.obj so it just opens it, which should be consistent regardless of the mtime

Does that seem correct? Now I get that there are other types of dependencies in Waf such as `add_manual_dependency()`. I suppose if there are dependencies that rely on file attributes like mtime before deciding to read and check the hash then it could be problematic on NFS. But all that being said, it isn't apparent to me that there is a problem with HostB reading an old file if we know that it shouldn't start until the upstream task is done, and that the upstream task would have called `close()` to sync the file to disk.

**Comment by sarvi** [comment]
I wrote my task that used dask to run the remote job.

I ran into some intermittent incremental build problems relating to older version of the files being read by some jobs. But didnt have a chance trouble shoot further.

**Comment by ita1024** [comment]
Note: the `mtime` value is used in the installation phase (hashing the target files is equivalent to making a full copy), but not in the build phase.

**Comment by justinfx** [comment]
@ita1024 could that mean that NFS caching shouldn't be much of an issue, if distributed hosts are just performing the subprocess of the build tasks, and the installation tasks would always happen from the same NFS client that is running waf?

**Comment by ita1024** [comment]
@justinfx That assumes a network filesystem that does not cache reads or writes and makes files immediately visible after they are closed. Try and see!
